FROM ghcr.io/kubevda/vdimage-arch-xfce-base:latest

RUN set -exu \
  && pacman --noconfirm -Syu \
  && pacman --noconfirm -Syu \
    cuda \
    cuda-tools \
    python-cuda \
    libvdpau \
    nvidia-utils \
    nvtop \
    opencl-nvidia \
    egl-x11 \
    code \
    curl \
    firefox \
    git \
    nano \
    wget \
    xfce4-goodies \
    nvidia

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility

COPY rootfs.cuda /
