FROM docker.io/archlinux:base

RUN set -exu \
  && pacman -Syyu \
  && pacman -Syy \
    git \
    curl \
    wget \
    nano \
    xfce4 \
    xfce4-goodies \
    supervisor \
    dbus \
    tigervnc \
    mesa

COPY rootfs /

CMD ["/bin/bash", "/entrypoint.sh"]
