FROM docker.io/archlinux:base

RUN set -exu \
  && pacman --noconfirm -Syyu \
  && pacman --noconfirm -Syy \
    dbus \
    mesa \
    sudo \
    supervisor \
    tigervnc \
    xfce4 \
    xorg \
    virtualgl

COPY rootfs.base /

CMD ["/bin/bash", "/entrypoint.sh"]
